version: '3'
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory.kirillian.tv'
    image: 'wolveix/satisfactory-server:latest'
    env_file:
    - .env
    ports:
      - '7777:7777/udp'
      - '15000:15000/udp'
      - '15777:15777/udp'
    volumes:
      - './config:/config'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 12G
