version: '3.2'

services:
  main:
    image: itzg/minecraft-server
    container_name: 'minecraftserver'
    env_file: .env
    environment:
      EULA: "TRUE"
      REPLACE_ENV_VARIABLES: "TRUE"
      ENV_VARIABLE_PREFIX: "CONFIG_"
      ENABLE_ROLLING_LOGS: "true"
      USE_AIKAR_FLAGS: "true"
      VERSION: "LATEST"
      TYPE: "PAPER"
      MEMORY: "2G"
      CONFIG_DISCORD_BOT_TOKEN: ${CONFIG_DISCORD_BOT_TOKEN}
      CONFIG_DISCORD_SERVER_ID: ${CONFIG_DISCORD_SERVER_ID}
      CONFIG_DISCORD_PRIMARY_CHANNEL_ID: ${CONFIG_DISCORD_PRIMARY_CHANNEL_ID}
      CONFIG_DISCORD_STAFF_CHANNEL_ID: ${CONFIG_DISCORD_STAFF_CHANNEL_ID}
      CONFIG_MOTD_LINE: ${CONFIG_MOTD_LINE}
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "${HOST_MINECRAFT_PORT}:25565"
      - "${HOST_BEDROCK_PORT}:19132/udp"
      - "${HOST_DYNMAP_PORT}:8123"
    volumes:
      - ./minecraft-data:/data
      - ./plugins:/data/plugins
      - ./config:/data/config
