version: '3.2'

services:
  main:
    image: itzg/minecraft-server
    container_name: 'minecraftserver'
    env_file: .env
    environment:
      EULA: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "${HOST_MINECRAFT_PORT}:25565"
    volumes:
      - ./minecraft-data:/data
      - ./plugins:/data/plugins
      - ./config:/data/config
